/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Application.ServiceLocator;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import Model.ImageModel;
import java.awt.Color;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import oracle.jdbc.pool.OracleDataSource;
/**
 *
 * @author doria
 */
public class searchResults extends javax.swing.JPanel {
private int id;
    /**
     * Creates new form serchresua
     * @param id
     */
    public searchResults(Integer id) {
        initComponents();
         setImageId(id);
           myInit();
    }
public int getid() {
        return id;
    }
    searchResults() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
   /**
     *设置要进行搜索的图像
     *
     * @param id id 图片
     */
   
    public void setImageId(Integer id) {
        this.imageId = id;
    }
  public void myInit() {
        result_container.setLayout(new BoxLayout(result_container, BoxLayout.Y_AXIS));
        ModelImage = new ImageModel();
        System.out.println(ModelImage);    
        Map<Integer, myIcon> result = null;
        try {
            System.out.println("for ID: "+1);
            result = ModelImage.getTheMostSimilar(1, 0.3, 0.3, 0.1, 0.3);
            System.out.println("Found: "+result.size());
        } catch (SQLException ex) {
            Logger.getLogger(searchResults.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (result != null && result.size() > 0) {
            for (Map.Entry<Integer, myIcon> entry : result.entrySet()) {
                myIcon value = entry.getValue();
                //JLabel tm = new JLabel(value.getMyIcon());
                System.out.println("Score: " + value.getScore());
                value.setIcon(value.getIcon());
                value.setText(value.getScoreAsString());
                value.setToolTipText("The smaller the score, the more similar the picture");
                result_container.add(value);
                System.out.println(value);
            }
        } else if(result.size() <= 0){
            JLabel warn = new JLabel("No similar images! There is probably a single image in the database");
            String path = "/Info.png";
            ImageIcon i = new ImageIcon(getClass().getResource(path));
            warn.setIcon(i);
            warn.setBackground(Color.LIGHT_GRAY);
            result_container.add(warn);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        result_container = new javax.swing.JPanel();

        jScrollPane1.setViewportView(result_container);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel result_container;
    // End of variables declaration//GEN-END:variables
 private Integer imageId;
 private ImageModel ModelImage;

    void pack() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
 
}
